log:
  path: ./logs
  fileName: log

push:
  - label: dd
    value: xxx

noti:
  - pro: 10118 #省
    district: 06 #市
    city: 08 #区
    info: 固始县 #展示标识
    alarm: true #是否预警
    remind: true #前一天有雨提醒时间
    report: true #当天预报时间
  - pro: 10102
    district: 01
    city:
    info: 上海市
    alarm: true
    remind: true
    report: true
  - pro: 10118
    district: 01
    city: 01
    info: 郑州市
    alarm: true
    remind: true
    report: true